[General]
Name=YouTube-Coding

[Output]
Mode=Advanced
FilenameFormatting=Coding-%CCYY-%MM-%DD_%hh-%mm-%ss
DelayEnable=false
DelaySec=20
DelayPreserve=true
Reconnect=true
RetryDelay=2
MaxRetries=25
BindIP=default
IPFamily=IPv4+IPv6
NewSocketLoopEnable=false
LowLatencyEnable=false

[Stream1]
IgnoreRecommended=false
MultitrackVideoMaximumAggregateBitrateAuto=true
MultitrackVideoMaximumVideoTracksAuto=true
EnableMultitrackVideo=false

[SimpleOutput]
FilePath=/home/spy4x/Videos
RecFormat2=mkv
VBitrate=2500
ABitrate=160
UseAdvanced=true
Preset=veryfast
NVENCPreset2=p5
RecQuality=Small
RecRB=false
RecRBTime=20
RecRBSize=512
RecRBPrefix=Replay
StreamAudioEncoder=aac
RecAudioEncoder=aac
RecTracks=1
StreamEncoder=ffmpeg_openh264
RecEncoder=ffmpeg_openh264

[AdvOut]
ApplyServiceSettings=true
UseRescale=false
TrackIndex=1
VodTrackIndex=2
Encoder=av1_ffmpeg_vaapi
RecType=Standard
RecFilePath=/home/spy4x/recordings
RecFormat2=mkv
RecUseRescale=false
RecTracks=1
RecEncoder=av1_ffmpeg_vaapi
FLVTrack=1
StreamMultiTrackAudioMixes=1
FFOutputToFile=false
FFFilePath=/home/spy4x/recordings
FFVBitrate=2500
FFVGOPSize=250
FFUseRescale=false
FFIgnoreCompat=false
FFABitrate=160
FFAudioMixes=1
Track1Bitrate=160
Track2Bitrate=160
Track3Bitrate=160
Track4Bitrate=160
Track5Bitrate=160
Track6Bitrate=160
RecSplitFileTime=15
RecSplitFileSize=2048
RecRB=false
RecRBTime=20
RecRBSize=512
AudioEncoder=libfdk_aac
RecAudioEncoder=libfdk_aac
RecSplitFileType=Time
FFFormat=
FFFormatMimeType=
FFVEncoderId=0
FFVEncoder=
FFAEncoderId=0
FFAEncoder=
RecSplitResetTimestamp=true
AutoRemux=true
FFExtension=mp4

[VideoEncoder]
rate_control=CQP
cqp=22
target_bitrate=0
bitrate=25000
keyint=120
bframes=2
bframe_size=2
profile=1
; tier=0 (Main) for compatibility, 1 (Main10) if monitor is HDR.
; For AV1, "profile" 0 = Main (8-bit), 1 = High (8-bit), 2 = Professional.
tier=0
level=0
qp_i=22
qp_p=22
qp_b=22
width=3840
height=2160
format=1
dither=0
gpu=0

[Video]
BaseCX=3840
BaseCY=2160
OutputCX=3840
OutputCY=2160
FPSType=0
FPSCommon=30
FPSInt=30
FPSNum=30
FPSDen=1
ScaleType=bicubic
ColorFormat=NV12
ColorSpace=709
ColorRange=Partial
SdrWhiteLevel=300
HdrNominalPeakLevel=1000

[Audio]
MonitoringDeviceId=default
MonitoringDeviceName=Default
SampleRate=48000
ChannelSetup=Stereo
MeterDecayRate=23.53
PeakMeterType=0

[Panels]
CookieId=879CDCDFE9342FC9

[Hotkeys]
OBSBasic.StartStreaming={"bindings":[]}
OBSBasic.StartRecording={"bindings":[{"key":"OBS_KEY_F9"}]}
OBSBasic.StopRecording={"bindings":[{"key":"OBS_KEY_F9"}]}
OBSBasic.PauseRecording={"bindings":[{"key":"OBS_KEY_F10"}]}
OBSBasic.UnpauseRecording={"bindings":[{"key":"OBS_KEY_F10"}]}
